### ISSUE TITLE
I am not able to see the metrics on the browser

### ISSUE THREAD

**Issue by rkhemka24** [mbolek/locust_exporter#8]
Hi,
I am getting following error on terminal (where my locust_exporter is running),  when trying  to open the url localhost:8000 

Traceback (most recent call last):
  File "/Users/locust_exporter.py", line 70, in <module>
    REGISTRY.register(LocustCollector(str(sys.argv[2])))
  File "/Users/.venv/lib/python3.9/site-packages/prometheus_client/registry.py", line 26, in register
    names = self._get_names(collector)
  File "/Users/.venv/lib/python3.9/site-packages/prometheus_client/registry.py", line 66, in _get_names
    for metric in desc_func():
  File "/Users/locust_exporter.py", line 35, in collect
    metric.add_sample('locust_errors', value=err['occurences'], labels={'path':err['name'], 'method':err['method']})
KeyError: 'occurences'

FYI  command used on terminal to run locust_exporter is [./locus_exporter 8000 localhost:8089] and also Locust is running on browser.

Please tell how to solve this issue

**Comment by rkhemka24** [comment]
@kirknorthrop @mbolek

**Comment by rkhemka24** [comment]
_Error Trace:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/locust_exporter/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 118, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/Users/locust_exporter/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 100, in _bake_output
    output = encoder(registry)
  File "/Users/locust_exporter/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 202, in generate_latest
    output.append(sample_line(s))
  File "/Users/locust_exporter/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 159, in sample_line
    ['{}="{}"'.format(
  File "/Users/locust_exporter/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 160, in <listcomp>
    k, v.replace('\\', r'\\').replace('\n', r'\n').replace('"', r'\"'))
AttributeError: ("'NoneType' object has no attribute 'replace'", Metric(locust_requests_avg_content_length, Locust requests avg_content_length, gauge, , [Sample(name='locust_requests_avg_content_length', labels={'path': '/api/test, 'method': 'POST'}, value=165.0, timestamp=None, exemplar=None), Sample(name='locust_requests_avg_content_length', labels={'path': 'Aggregated', 'method': None}, value=165.0, timestamp=None, exemplar=None)]))_

**Comment by rkhemka24** [comment]
Created the pull request for the fix , please review and merge the changes .
Close the issue once the changes are merged.
